version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "02:00"
      timezone: "Asia/Tokyo"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 10
    groups:
      dev-dependencies:
        patterns:
          - "@anthropic-ai/*"
          - "@cybozu/*"
          - "@types/*"
          - "@vitest/*"
          - "eslint*"
          - "prettier"
          - "tsx"
          - "typescript"
          - "vitest"
        update-types:
          - "minor"
          - "patch"
      production-dependencies:
        patterns:
          - "@js-temporal/*"
          - "@modelcontextprotocol/*"
          - "undici"
          - "zod"
        update-types:
          - "minor"
          - "patch"
    labels:
      - "dependencies"
    allow:
      - dependency-type: "all"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "Asia/Tokyo"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "cicd"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Asia/Tokyo"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "cicd"
