name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Node
        uses: actions/setup-node@v5
        with:
          node-version-file: .node-version
          cache: "npm"

      - name: Run tests
        run: |
          npm install --frozen-lockfile
          npm test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Node
        uses: actions/setup-node@v5
        with:
          node-version-file: .node-version
          cache: "npm"

      - name: Run lint checks
        run: |
          npm install --frozen-lockfile
          npm run lint

  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Node
        uses: actions/setup-node@v5
        with:
          node-version-file: .node-version
          cache: "npm"

      - name: Run type checks
        run: |
          npm install --frozen-lockfile
          npm run typecheck

  check-dxt:
    name: DXT Manifest Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Node
        uses: actions/setup-node@v5
        with:
          node-version-file: .node-version
          cache: "npm"

      - name: Validate manifest.json
        run: |
          npm install --frozen-lockfile
          npm run check:dxt

  license-check:
    name: Dependency License Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Node
        uses: actions/setup-node@v5
        with:
          node-version-file: .node-version
          cache: "npm"

      - name: Analyze unconfirmed licenses
        run: |
          npm install --frozen-lockfile
          npm run license:analyze

  build-container-image-test:
    name: Build Container Image Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3

      - name: Build Docker image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          context: .
          file: ./Dockerfile
          platforms: "linux/amd64,linux/arm64"
          push: false
        env:
          DOCKER_BUILD_SUMMARY: false
