name: Publish Dev Image
on:
  push:
    branches:
      - main

jobs:
  build-and-publish-container:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/reusable-publish-image.yml
    with:
      tags: dev
      push: true
