name: Update Release Draft

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release-draft:
    name: Create Release Draft
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    outputs:
      tag_name: ${{ steps.release-drafter.outputs.tag_name }}
    steps:
      - name: Run Release Drafter
        uses: release-drafter/release-drafter@139054aeaa9adc52ab36ddf67437541f039b88e2 # v7.1.1
        id: release-drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-mcpb:
    name: Build MCPB Package
    needs:
      - release-draft
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: "pnpm"

      - name: Build MCPB
        run: |
          pnpm install --frozen-lockfile
          pnpm run build:mcpb

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: garoon-mcp-server.mcpb
          path: build/garoon-mcp-server.mcpb

  upload-binaries:
    name: Upload MCPB Package to Release Draft
    needs:
      - build-mcpb
      - release-draft
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          path: ./artifacts

      - name: Upload MCPB package
        run: |
          gh release upload ${{ needs.release-draft.outputs.tag_name }} ./artifacts/garoon-mcp-server.mcpb --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
