name: Update Release Draft

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release-draft:
    name: Create Release Draft
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    outputs:
      tag_name: ${{ steps.release-drafter.outputs.tag_name }}
    steps:
      - name: Run Release Drafter
        uses: release-drafter/release-drafter@4d75298e00d9e34c483e5ff8c68d0ea1c1940c1e # v7.5.1
        id: release-drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-mcpb:
    name: Build MCPB Package
    needs:
      - release-draft
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

      - name: Set up Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: .node-version
          cache: "pnpm"

      - name: Build MCPB
        run: |
          pnpm install --frozen-lockfile
          pnpm run build:mcpb

      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: garoon-mcp-server.mcpb
          path: build/garoon-mcp-server.mcpb

  upload-binaries:
    name: Upload MCPB Package to Release Draft
    needs:
      - build-mcpb
      - release-draft
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Download artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: ./artifacts

      - name: Upload MCPB package
        run: |
          gh release upload ${{ needs.release-draft.outputs.tag_name }} ./artifacts/garoon-mcp-server.mcpb --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
